package Excception_handling;

public class try_catch {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		try {
			System.out.println(10/0);

//			System.out.println(10/0);
		}
		catch(Exception a) {
			System.out.println("dividing by 0");
		}
	

	}

}
